apiVersion: v1
kind: ConfigMap
metadata:
  name: ajwa-config
  namespace: ajwa-commerce
data:
  NODE_ENV: "production"
  PORT: "8000"
  AI_PORT: "5001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ajwa_ai_commerce"
  AI_SERVICE_HOST: "ai-service"
  AI_SERVICE_PORT: "5001"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  UPI_VPA: "ajwadryfruits@okaxis"
