apiVersion: v1
kind: Secret
metadata:
  name: ajwa-secrets
  namespace: ajwa-commerce
type: Opaque
stringData:
  DB_USER: "ajwa_admin"
  DB_PASSWORD: "ajwa_secure_password_2026"
  JWT_SECRET: "ajwa_jwt_production_secret_key_cloud_native_2026"
  RAZORPAY_KEY_ID: "rzp_test_ajwa_dry_fruits_live"
  RAZORPAY_KEY_SECRET: "rzp_secret_ajwa_dry_fruits_live"
  STRIPE_API_KEY: "pk_test_mock_stripe_key"
  STRIPE_SECRET_KEY: "sk_test_mock_stripe_key"
