apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ajwa-ingress
  namespace: ajwa-commerce
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: ajwa-commerce.local
      http:
        paths:
          # Route AI Microservice Directly
          - path: /api/v1/ai
            pathType: Prefix
            backend:
              service:
                name: ai-service
                port:
                  number: 5001
          # Route Backend API Gateway
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          # Route Uploaded Media
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          # Route Customer Frontend SPA
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
